# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gaitGUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1122, 734)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1121, 671))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(10, 10, 241, 151))
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 0, 211, 151))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_13 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_13.setTabletTracking(False)
        self.pushButton_13.setCheckable(False)
        self.pushButton_13.setAutoExclusive(False)
        self.pushButton_13.setAutoDefault(False)
        self.pushButton_13.setDefault(False)
        self.pushButton_13.setFlat(False)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_5.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_14.setCheckable(False)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_5.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_5.addWidget(self.pushButton_15)
        self.frame_4 = QtWidgets.QFrame(self.page)
        self.frame_4.setGeometry(QtCore.QRect(10, 180, 241, 491))
        self.frame_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 211, 471))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 121, 19))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 40, 111, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 60, 115, 19))
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 80, 191, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_14.addWidget(self.pushButton_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_14.addWidget(self.lineEdit_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 20, 115, 19))
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 40, 115, 19))
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 90, 181, 22))
        self.horizontalSlider.setMaximum(200)
        self.horizontalSlider.setSingleStep(10)
        self.horizontalSlider.setProperty("value", 50)
        self.horizontalSlider.setSliderPosition(50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(10)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(60, 70, 72, 15))
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 139, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_2.setMaximum(10)
        self.spinBox_2.setProperty("value", 2)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 50, 139, 26))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_3.setMaximum(10)
        self.spinBox_3.setProperty("value", 2)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_5.addWidget(self.spinBox_3)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 80, 115, 26))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spinBox.setMaximum(10)
        self.spinBox.setProperty("value", 2)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_4)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.frame_3 = QtWidgets.QFrame(self.page)
        self.frame_3.setGeometry(QtCore.QRect(350, 530, 401, 81))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frame_3)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 391, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        self.pushButton_28 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_4.addWidget(self.pushButton_28)
        self.pushButton_10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_4.addWidget(self.pushButton_10)
        self.progressBar = QtWidgets.QProgressBar(self.page)
        self.progressBar.setGeometry(QtCore.QRect(330, 630, 741, 23))
        self.progressBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.progressBar.setAcceptDrops(False)
        self.progressBar.setProperty("value", 50)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.page)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(780, 540, 181, 95))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.line_7 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_4.addWidget(self.line_7)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_4.addItem(spacerItem)
        self.widget_4 = QtWidgets.QWidget(self.page)
        self.widget_4.setGeometry(QtCore.QRect(260, 0, 851, 525))
        self.widget_4.setBaseSize(QtCore.QSize(0, 0))
        self.widget_4.setTabletTracking(False)
        self.widget_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.widget_4.setAutoFillBackground(False)
        self.widget_4.setObjectName("widget_4")
        self.label_12 = QtWidgets.QLabel(self.widget_4)
        self.label_12.setGeometry(QtCore.QRect(80, 10, 681, 511))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setGeometry(QtCore.QRect(460, 530, 331, 91))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setProperty("idex", 0)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(40, 20, 251, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_11 = QtWidgets.QFrame(self.page_2)
        self.frame_11.setGeometry(QtCore.QRect(10, 180, 241, 491))
        self.frame_11.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_11)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 211, 471))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        self.groupBox_7 = QtWidgets.QGroupBox(self.verticalLayoutWidget_3)
        self.groupBox_7.setObjectName("groupBox_7")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_11.setGeometry(QtCore.QRect(10, 20, 121, 19))
        self.radioButton_11.setChecked(True)
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_12.setGeometry(QtCore.QRect(10, 40, 111, 19))
        self.radioButton_12.setObjectName("radioButton_12")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 130, 209, 271))
        self.groupBox_8.setObjectName("groupBox_8")
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_14.setGeometry(QtCore.QRect(10, 20, 115, 19))
        self.radioButton_14.setChecked(True)
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_15.setEnabled(False)
        self.radioButton_15.setGeometry(QtCore.QRect(10, 40, 115, 19))
        self.radioButton_15.setObjectName("radioButton_15")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.groupBox_8)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(10, 90, 181, 22))
        self.horizontalSlider_3.setMaximum(100)
        self.horizontalSlider_3.setSingleStep(10)
        self.horizontalSlider_3.setProperty("value", 10)
        self.horizontalSlider_3.setSliderPosition(10)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setInvertedAppearance(False)
        self.horizontalSlider_3.setInvertedControls(False)
        self.horizontalSlider_3.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_3.setTickInterval(10)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_8)
        self.label_9.setGeometry(QtCore.QRect(60, 70, 72, 15))
        self.label_9.setObjectName("label_9")
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_13.setEnabled(False)
        self.radioButton_13.setGeometry(QtCore.QRect(90, 20, 115, 19))
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_16.setEnabled(False)
        self.radioButton_16.setGeometry(QtCore.QRect(90, 40, 115, 19))
        self.radioButton_16.setObjectName("radioButton_16")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_8)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 130, 158, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMinimum(0.1)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setProperty("value", 0.1)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_13.addWidget(self.doubleSpinBox)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox.setGeometry(QtCore.QRect(10, 180, 192, 19))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 210, 161, 19))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_7)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 80, 191, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_11.addWidget(self.pushButton_5)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_11.addWidget(self.lineEdit_3)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_6.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_3.addWidget(self.pushButton_6)
        self.line_6 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_3.addWidget(self.line_6)
        self.progressBar_3 = QtWidgets.QProgressBar(self.page_2)
        self.progressBar_3.setGeometry(QtCore.QRect(330, 630, 721, 23))
        self.progressBar_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.progressBar_3.setAcceptDrops(False)
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName("progressBar_3")
        self.frame_12 = QtWidgets.QFrame(self.page_2)
        self.frame_12.setGeometry(QtCore.QRect(10, 10, 241, 151))
        self.frame_12.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.frame_12)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 0, 211, 151))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_25 = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.pushButton_25.setTabletTracking(False)
        self.pushButton_25.setCheckable(False)
        self.pushButton_25.setAutoExclusive(False)
        self.pushButton_25.setAutoDefault(False)
        self.pushButton_25.setDefault(False)
        self.pushButton_25.setFlat(False)
        self.pushButton_25.setObjectName("pushButton_25")
        self.verticalLayout_7.addWidget(self.pushButton_25)
        self.pushButton_26 = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.pushButton_26.setCheckable(False)
        self.pushButton_26.setObjectName("pushButton_26")
        self.verticalLayout_7.addWidget(self.pushButton_26)
        self.pushButton_27 = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.pushButton_27.setObjectName("pushButton_27")
        self.verticalLayout_7.addWidget(self.pushButton_27)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea_2.setGeometry(QtCore.QRect(260, 10, 851, 521))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 200, 2000))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(200, 2000))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setGeometry(QtCore.QRect(-20, 0, 851, 2000))
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(False)
        self.label_11.setIndent(-1)
        self.label_11.setObjectName("label_11")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.widget = QtWidgets.QWidget(self.page_2)
        self.widget.setEnabled(False)
        self.widget.setGeometry(QtCore.QRect(290, 540, 791, 81))
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(160, 10, 471, 61))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_15.addWidget(self.lineEdit_5)
        self.pushButton_21 = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_15.addWidget(self.pushButton_21)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.frame_7 = QtWidgets.QFrame(self.page_3)
        self.frame_7.setGeometry(QtCore.QRect(10, 180, 241, 491))
        self.frame_7.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_7)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 211, 471))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 20, 121, 19))
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_7.setGeometry(QtCore.QRect(10, 40, 111, 19))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_8.setGeometry(QtCore.QRect(10, 60, 115, 19))
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 80, 191, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_12.addWidget(self.pushButton_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_12.addWidget(self.lineEdit_4)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_9.setGeometry(QtCore.QRect(10, 20, 115, 19))
        self.radioButton_9.setChecked(True)
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_10.setGeometry(QtCore.QRect(10, 40, 115, 19))
        self.radioButton_10.setObjectName("radioButton_10")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(10, 90, 181, 22))
        self.horizontalSlider_2.setMaximum(200)
        self.horizontalSlider_2.setSingleStep(10)
        self.horizontalSlider_2.setProperty("value", 50)
        self.horizontalSlider_2.setSliderPosition(50)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setInvertedAppearance(False)
        self.horizontalSlider_2.setInvertedControls(False)
        self.horizontalSlider_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(60, 70, 72, 15))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 20, 139, 26))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.spinBox_5 = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_5.setMaximum(10)
        self.spinBox_5.setProperty("value", 2)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_9.addWidget(self.spinBox_5)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 50, 139, 26))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.spinBox_6 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_6.setMaximum(10)
        self.spinBox_6.setProperty("value", 2)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_10.addWidget(self.spinBox_6)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 80, 115, 26))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.spinBox_4 = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_4.setMaximum(10)
        self.spinBox_4.setProperty("value", 2)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_8.addWidget(self.spinBox_4)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_4.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.frame_8 = QtWidgets.QFrame(self.page_3)
        self.frame_8.setGeometry(QtCore.QRect(10, 10, 241, 151))
        self.frame_8.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.frame_8)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 0, 211, 151))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_18 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_18.setTabletTracking(False)
        self.pushButton_18.setCheckable(False)
        self.pushButton_18.setAutoExclusive(False)
        self.pushButton_18.setAutoDefault(False)
        self.pushButton_18.setDefault(False)
        self.pushButton_18.setFlat(False)
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_6.addWidget(self.pushButton_18)
        self.pushButton_19 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_19.setCheckable(False)
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_6.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_6.addWidget(self.pushButton_20)
        self.frame_5 = QtWidgets.QFrame(self.page_3)
        self.frame_5.setGeometry(QtCore.QRect(470, 520, 311, 81))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.frame_5)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 291, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_11 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_6.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_6.addWidget(self.pushButton_12)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 331, 81))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setProperty("idex", 0)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.frame_6)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 291, 51))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_16 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_7.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_7.addWidget(self.pushButton_17)
        self.widget_5 = QtWidgets.QWidget(self.page_3)
        self.widget_5.setGeometry(QtCore.QRect(260, 10, 851, 525))
        self.widget_5.setObjectName("widget_5")
        self.label_14 = QtWidgets.QLabel(self.widget_5)
        self.label_14.setGeometry(QtCore.QRect(0, 0, 401, 291))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_5)
        self.tabWidget.setGeometry(QtCore.QRect(0, 310, 851, 211))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(480, 10, 301, 191))
        self.label_18.setScaledContents(True)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(30, 0, 281, 201))
        self.label_16.setScaledContents(True)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(340, 15, 111, 191))
        self.label_17.setObjectName("label_17")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_19 = QtWidgets.QLabel(self.widget_5)
        self.label_19.setGeometry(QtCore.QRect(420, 0, 401, 291))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1122, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.action4 = QtWidgets.QAction(MainWindow)
        self.action4.setObjectName("action4")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action1)
        self.menu.addAction(self.action2)
        self.menu_2.addAction(self.action3)
        self.menu_2.addAction(self.action4)
        self.menu_2.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.radioButton.clicked['bool'].connect(self.pushButton_2.setEnabled)
        self.radioButton_2.clicked['bool'].connect(self.pushButton_2.setDisabled)
        self.radioButton_3.clicked['bool'].connect(self.pushButton_2.setDisabled)
        self.radioButton_11.clicked['bool'].connect(self.pushButton_5.setDisabled)
        self.radioButton_12.clicked['bool'].connect(self.pushButton_5.setEnabled)
        self.radioButton_6.clicked['bool'].connect(self.pushButton_3.setEnabled)
        self.radioButton_7.clicked['bool'].connect(self.pushButton_3.setDisabled)
        self.radioButton_8.clicked['bool'].connect(self.pushButton_3.setDisabled)
        self.radioButton.clicked['bool'].connect(self.frame_2.setVisible)
        self.radioButton_2.clicked['bool'].connect(self.frame_2.setHidden)
        self.radioButton_3.clicked['bool'].connect(self.frame_2.setHidden)
        self.radioButton.clicked['bool'].connect(self.frame_3.setHidden)
        self.radioButton_2.clicked['bool'].connect(self.frame_3.setVisible)
        self.radioButton_3.clicked['bool'].connect(self.frame_3.setVisible)
        self.radioButton.clicked['bool'].connect(self.lineEdit_2.setEnabled)
        self.radioButton_2.clicked['bool'].connect(self.lineEdit_2.setDisabled)
        self.radioButton_3.clicked['bool'].connect(self.lineEdit_2.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gait recognition"))
        self.pushButton_13.setText(_translate("MainWindow", "步态录入"))
        self.pushButton_14.setText(_translate("MainWindow", "步态训练"))
        self.pushButton_15.setText(_translate("MainWindow", "步态识别"))
        self.groupBox.setTitle(_translate("MainWindow", "视频输入方式"))
        self.radioButton.setText(_translate("MainWindow", "视频文件"))
        self.radioButton_2.setText(_translate("MainWindow", "本机摄像头"))
        self.radioButton_3.setText(_translate("MainWindow", "外置摄像头"))
        self.pushButton_2.setText(_translate("MainWindow", "选择文件"))
        self.groupBox_3.setTitle(_translate("MainWindow", "背景训练模式"))
        self.radioButton_4.setText(_translate("MainWindow", "KNN"))
        self.radioButton_5.setText(_translate("MainWindow", "MOG2"))
        self.label_4.setText(_translate("MainWindow", "训练帧数"))
        self.groupBox_2.setTitle(_translate("MainWindow", "降噪设置"))
        self.label_2.setText(_translate("MainWindow", "膨胀系数(X)"))
        self.label_3.setText(_translate("MainWindow", "膨胀系数(Y)"))
        self.label.setText(_translate("MainWindow", "腐蚀系数"))
        self.checkBox_3.setText(_translate("MainWindow", "录入结束后生成GEI"))
        self.checkBox_4.setText(_translate("MainWindow", "录入结束后自动打包"))
        self.pushButton.setText(_translate("MainWindow", "开始录入"))
        self.pushButton_9.setText(_translate("MainWindow", "预览"))
        self.pushButton_28.setText(_translate("MainWindow", "录制"))
        self.pushButton_10.setText(_translate("MainWindow", "停止"))
        self.label_13.setText(_translate("MainWindow", "输入姓名"))
        self.label_12.setText(_translate("MainWindow", "请选择视频源..."))
        self.pushButton_7.setText(_translate("MainWindow", "预览"))
        self.pushButton_8.setText(_translate("MainWindow", "停止"))
        self.groupBox_7.setTitle(_translate("MainWindow", "步态数据输入方式"))
        self.radioButton_11.setText(_translate("MainWindow", "默认文件夹"))
        self.radioButton_12.setText(_translate("MainWindow", "自选文件夹"))
        self.groupBox_8.setTitle(_translate("MainWindow", "步态训练参数"))
        self.radioButton_14.setText(_translate("MainWindow", "90°"))
        self.radioButton_15.setText(_translate("MainWindow", "45°"))
        self.label_9.setText(_translate("MainWindow", "训练次数"))
        self.radioButton_13.setText(_translate("MainWindow", "0°"))
        self.radioButton_16.setText(_translate("MainWindow", "180°"))
        self.label_10.setText(_translate("MainWindow", "测试集比例"))
        self.checkBox.setText(_translate("MainWindow", "生成流程图表"))
        self.checkBox_2.setText(_translate("MainWindow", "训练结束后进行评估"))
        self.pushButton_5.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_6.setText(_translate("MainWindow", "开始训练"))
        self.pushButton_25.setText(_translate("MainWindow", "步态录入"))
        self.pushButton_26.setText(_translate("MainWindow", "步态训练"))
        self.pushButton_27.setText(_translate("MainWindow", "步态识别"))
        self.label_11.setText(_translate("MainWindow", "等待模型训练完毕..."))
        self.label_15.setText(_translate("MainWindow", "详细数据已发布在"))
        self.lineEdit_5.setText(_translate("MainWindow", "http://localhost:6006"))
        self.pushButton_21.setText(_translate("MainWindow", "立即前往"))
        self.groupBox_4.setTitle(_translate("MainWindow", "视频输入方式"))
        self.radioButton_6.setText(_translate("MainWindow", "视频文件"))
        self.radioButton_7.setText(_translate("MainWindow", "本机摄像头"))
        self.radioButton_8.setText(_translate("MainWindow", "外置摄像头"))
        self.pushButton_3.setText(_translate("MainWindow", "选择文件"))
        self.groupBox_5.setTitle(_translate("MainWindow", "背景训练模式"))
        self.radioButton_9.setText(_translate("MainWindow", "KNN"))
        self.radioButton_10.setText(_translate("MainWindow", "MOG2"))
        self.label_5.setText(_translate("MainWindow", "训练帧数"))
        self.groupBox_6.setTitle(_translate("MainWindow", "降噪设置"))
        self.label_7.setText(_translate("MainWindow", "膨胀系数(X)"))
        self.label_8.setText(_translate("MainWindow", "膨胀系数(Y)"))
        self.label_6.setText(_translate("MainWindow", "腐蚀系数"))
        self.pushButton_4.setText(_translate("MainWindow", "开始识别"))
        self.pushButton_18.setText(_translate("MainWindow", "步态录入"))
        self.pushButton_19.setText(_translate("MainWindow", "步态训练"))
        self.pushButton_20.setText(_translate("MainWindow", "步态识别"))
        self.pushButton_11.setText(_translate("MainWindow", "开始"))
        self.pushButton_12.setText(_translate("MainWindow", "停止"))
        self.pushButton_16.setText(_translate("MainWindow", "预览"))
        self.pushButton_17.setText(_translate("MainWindow", "停止"))
        self.label_14.setText(_translate("MainWindow", "视频等待加载..."))
        self.label_18.setText(_translate("MainWindow", "gei"))
        self.label_16.setText(_translate("MainWindow", "cgei"))
        self.label_17.setText(_translate("MainWindow", "<=current\n"
"\n"
"\n"
"perdict=>\n"
"\n"
"\n"
"name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.label_19.setText(_translate("MainWindow", "视频等待加载..."))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.action1.setText(_translate("MainWindow", "打开视频帧文件夹"))
        self.action2.setText(_translate("MainWindow", "打开GEI文件夹"))
        self.action3.setText(_translate("MainWindow", "视频帧转为gei"))
        self.action4.setText(_translate("MainWindow", "GEI打包为训练数据"))
        self.action.setText(_translate("MainWindow", "列表管理"))
